id: P000076
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཆོས་ཚུལ་སྣ་ཚོགས་ལས་བརྩམས་ཏེ་འབེལ་གཏམ་དུ་བགྱིས་པའི་རབས་མེ་ཏོག་ཆུན་འཕྱང་ལགས།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
  id: TSD-TSE-13
web_metadata:
  title:
    en: Flower Garlands:A Discourse on Various Dharma Topics
    bo: ཆོས་ཚུལ་སྣ་ཚོགས་ལས་བརྩམས་ཏེ་འབེལ་གཏམ་དུ་བགྱིས་པའི་རབས་མེ་ཏོག་ཆུན་འཕྱང་ལགས།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 13
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༡༣
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-13
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-13.epub
  description:
    en: ''
    bo: ''
